//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accenture.WebShop.SharedKernal.Resources{
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class WebShop {


		private static global::System.Resources.ResourceManager resourceMan;

private static global::System.Globalization.CultureInfo resourceCulture;

[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
internal
WebShop () {
}

/// <summary>
///   Returns the cached ResourceManager instance used by this class.
/// </summary>
[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
public static global::System.Resources.ResourceManager ResourceManager
{
	get
	{
		if (object.ReferenceEquals(resourceMan, null))
		{
			global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager($"Accenture.WebShop.SharedKernal.Resources.WebShop", typeof(WebShop).Assembly);
			resourceMan = temp;
		}
		return resourceMan;
	}
}

/// <summary>
///   Overrides the current thread's CurrentUICulture property for all
///   resource lookups using this strongly typed resource class.
/// </summary>
[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
public static global::System.Globalization.CultureInfo Culture
{
	get
	{
		return resourceCulture;
	}
	set
	{
		resourceCulture = value;
	}
}

/// <summary>
///   Looks up a localized string similar to Action.
/// </summary>
public static string Action
{
	get
	{
		return ResourceManager.GetString("Action", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Add.
/// </summary>
public static string Add
{
	get
	{
		return ResourceManager.GetString("Add", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to through various rows levels on data entities and operations..
/// </summary>
public static string AdministartionDescriptionPart2
{
	get
	{
		return ResourceManager.GetString("AdministartionDescriptionPart2", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Administration.
/// </summary>
public static string Administration
{
	get
	{
		return ResourceManager.GetString("Administration", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Provides capabilities to create and update access to.
/// </summary>
public static string AdministrationDescriptionPart1
{
	get
	{
		return ResourceManager.GetString("AdministrationDescriptionPart1", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Apply.
/// </summary>
public static string Apply
{
	get
	{
		return ResourceManager.GetString("Apply", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Audit History.
/// </summary>
public static string AuditHistory
{
	get
	{
		return ResourceManager.GetString("AuditHistory", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Cancel.
/// </summary>
public static string Cancel
{
	get
	{
		return ResourceManager.GetString("Cancel", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Something went wrong. Please try again later.
/// </summary>
public static string ErrorMsg
{
	get
	{
		return ResourceManager.GetString("ErrorMsg", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Provides capabilities to create and update access to entities through various rows levels on data entities and operations.
/// </summary>
public static string AdministrationDescription
{
	get
	{
		return ResourceManager.GetString("AdministrationDescription", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Choose Language.
/// </summary>
public static string ChooseLanguage
{
	get
	{
		return ResourceManager.GetString("ChooseLanguage", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Choose Theme.
/// </summary>
public static string ChooseTheme
{
	get
	{
		return ResourceManager.GetString("ChooseTheme", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Cookies Policy.
/// </summary>
public static string CookiesPolicy
{
	get
	{
		return ResourceManager.GetString("CookiesPolicy", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to © 2024 Accenture. All Rights Reserved. Accenture Confidential. For Internal Use Only..
/// </summary>
public static string CopyrightText
{
	get
	{
		return ResourceManager.GetString("CopyrightText", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Dashboard.
/// </summary>
public static string Dashboard
{
	get
	{
		return ResourceManager.GetString("Dashboard", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Delete.
/// </summary>
public static string Delete
{
	get
	{
		return ResourceManager.GetString("Delete", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Do you want to delete this.
/// </summary>
public static string DeleteConfirmationMsg
{
	get
	{
		return ResourceManager.GetString("DeleteConfirmationMsg", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Record deleted successfully.
/// </summary>
public static string DeletedSuccessfully
{
	get
	{
		return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to This record is referenced by a foreign key constraint. Unable to delete.
/// </summary>
public static string DeleteError
{
	get
	{
		return ResourceManager.GetString("DeleteError", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Details.
/// </summary>
public static string Details
{
	get
	{
		return ResourceManager.GetString("Details", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Combination already exists.
/// </summary>
public static string DuplicateErrorMsg
{
	get
	{
		return ResourceManager.GetString("DuplicateErrorMsg", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Edit.
/// </summary>
public static string Edit
{
	get
	{
		return ResourceManager.GetString("Edit", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Home.
/// </summary>
public static string Home
{
	get
	{
		return ResourceManager.GetString("Home", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to It&apos;s easy to write software that fulfills its users&apos; immediate needs but is difficult to extend and maintain. Such software becomes a burden for companies striving to remain competitive..
/// </summary>
public static string HomeBannerTitle
{
	get
	{
		return ResourceManager.GetString("HomeBannerTitle", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Rapid development of micro services &amp; monolithic apps.
/// </summary>
public static string HomePageListItem
{
	get
	{
		return ResourceManager.GetString("HomePageListItem", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Model-driven, business first development approach.
/// </summary>
public static string HomePageListItem1
{
	get
	{
		return ResourceManager.GetString("HomePageListItem1", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to High degree of app code, test and artifacts generation.
/// </summary>
public static string HomePageListItem2
{
	get
	{
		return ResourceManager.GetString("HomePageListItem2", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Unlike No-Code platforms you own your code.
/// </summary>
public static string HomePageListItem3
{
	get
	{
		return ResourceManager.GetString("HomePageListItem3", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Drag/drop integration with other accenture services.
/// </summary>
public static string HomePageListItem4
{
	get
	{
		return ResourceManager.GetString("HomePageListItem4", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Automated multi-cloud instance provisioning.
/// </summary>
public static string HomePageListItem5
{
	get
	{
		return ResourceManager.GetString("HomePageListItem5", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Built-in CI/CD support.
/// </summary>
public static string HomePageListItem6
{
	get
	{
		return ResourceManager.GetString("HomePageListItem6", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Choose tech-stack of your choice.
/// </summary>
public static string HomePageListItem7
{
	get
	{
		return ResourceManager.GetString("HomePageListItem7", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Collaboration &amp; innovation, not exclusion.
/// </summary>
public static string HomePageListItem8
{
	get
	{
		return ResourceManager.GetString("HomePageListItem8", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to supports following business features:.
/// </summary>
public static string HomeTitle
{
	get
	{
		return ResourceManager.GetString("HomeTitle", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Is Localized Standard Column.
/// </summary>
public static string IsLocalizedStandardColumn
{
	get
	{
		return ResourceManager.GetString("IsLocalizedStandardColumn", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Processing your request. Please wait....
/// </summary>
public static string LoaderText
{
	get
	{
		return ResourceManager.GetString("LoaderText", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to { &quot;Timestamp&quot;: {DateTime}, &quot;LogType&quot;:&quot;{logtype}&quot;, &quot;Message&quot;:&quot;{MessageText}&quot;, &quot;title&quot;:&quot;{title}&quot;, &quot;CorrelationUId&quot;:&quot;{correlationUId}&quot;, &quot;Exception&quot;:&quot;{exceptionMessage}&quot;, &quot;StackTrace&quot;:&quot;{jsonStacktrace}&quot;, &quot;AssemblyNamespace&quot;:&quot;{assemblyNamespace}&quot;, &quot;Component&quot;:&quot;{component}&quot;}.
/// </summary>
public static string LogTemplate
{
	get
	{
		return ResourceManager.GetString("LogTemplate", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Manage.
/// </summary>
public static string Manage
{
	get
	{
		return ResourceManager.GetString("Manage", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Manage Domains.
/// </summary>
public static string ManageDomains
{
	get
	{
		return ResourceManager.GetString("ManageDomains", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Manage Entities.
/// </summary>
public static string ManageEntities
{
	get
	{
		return ResourceManager.GetString("ManageEntities", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to It involves managing service composer platform efficiently. It ensures, platform and application are running efficiently and effectively..
/// </summary>
public static string ManageEntitiesDescription
{
	get
	{
		return ResourceManager.GetString("ManageEntitiesDescription", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to No.
/// </summary>
public static string No
{
	get
	{
		return ResourceManager.GetString("No", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to No Data Found.
/// </summary>
public static string NoDataFound
{
	get
	{
		return ResourceManager.GetString("NoDataFound", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Privacy Statement.
/// </summary>
public static string PrivacyStatement
{
	get
	{
		return ResourceManager.GetString("PrivacyStatement", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Proceed.
/// </summary>
public static string Proceed
{
	get
	{
		return ResourceManager.GetString("Proceed", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Save.
/// </summary>
public static string Save
{
	get
	{
		return ResourceManager.GetString("Save", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Data saved successfully.
/// </summary>
public static string SaveSuccess
{
	get
	{
		return ResourceManager.GetString("SaveSuccess", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Search.
/// </summary>
public static string Search
{
	get
	{
		return ResourceManager.GetString("Search", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Select.
/// </summary>
public static string Select
{
	get
	{
		return ResourceManager.GetString("Select", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Selected.
/// </summary>
public static string Selected
{
	get
	{
		return ResourceManager.GetString("Selected", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Service Composer.
/// </summary>
public static string ServiceComposerTitle
{
	get
	{
		return ResourceManager.GetString("ServiceComposerTitle", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Terms of Use.
/// </summary>
public static string TermsOfUse
{
	get
	{
		return ResourceManager.GetString("TermsOfUse", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Unsaved Changes.
/// </summary>
public static string UnsavedChanges
{
	get
	{
		return ResourceManager.GetString("UnsavedChanges", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to There are unsaved changes in the form. Do you want to lose the changes?.
/// </summary>
public static string UnsavedChangesMsg
{
	get
	{
		return ResourceManager.GetString("UnsavedChangesMsg", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to View.
/// </summary>
public static string View
{
	get
	{
		return ResourceManager.GetString("View", resourceCulture);
	}
}


/// <summary>
///   Looks up a localized string similar to Welcome.
/// </summary>
public static string Welcome
{
	get
	{
		return ResourceManager.GetString("Welcome", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Yes.
/// </summary>
public static string Yes
{
	get
	{
		return ResourceManager.GetString("Yes", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Code Composer.
/// </summary>
public static string CodeComposer
{
	get
	{
		return ResourceManager.GetString("CodeComposer", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Exception.
/// </summary>
public static string Exception
{
	get
	{
		return ResourceManager.GetString("Exception", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Start.
/// </summary>
public static string Start
{
	get
	{
		return ResourceManager.GetString("Start", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Stop.
/// </summary>
public static string Stop
{
	get
	{
		return ResourceManager.GetString("Stop", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Manage Entity.
/// </summary>
public static string ManageEntity1
{
	get
	{
		return ResourceManager.GetString("ManageEntity1", resourceCulture);
	}
}

/// <summary>
/// Looks up a localized string similar to Begin.
/// </summary>
public static string Begin
{
	get
	{
		return ResourceManager.GetString("Begin", resourceCulture);
	}
}

/// <summary>
/// Looks up a localized string similar to End.
/// </summary>
public static string End
{
	get
	{
		return ResourceManager.GetString("End", resourceCulture);
	}
}

/// <summary>
/// Looks up a localized string similar to Manage Schemas.
/// </summary>
public static string ManageSchemas
{
	get
	{
		return ResourceManager.GetString("ManageSchemas", resourceCulture);
	}
}

/// <summary>
/// Looks up a localized string similar to It involves managing database schemas efficiently.
/// </summary>
public static string ManageSchemasDescription
{
	get
	{
		return ResourceManager.GetString("ManageSchemasDescription", resourceCulture);
	}
}

/// <summary>
/// Looks up a localized string similar to Manage Features.
/// </summary>
public static string ManageFeatures
{
	get
	{
		return ResourceManager.GetString("ManageFeatures", resourceCulture);
	}
}

/// <summary>
/// Looks up a localized string similar to Manage Features Description.
/// </summary>
public static string ManageFeaturesDescription
{
	get
	{
		return ResourceManager.GetString("ManageFeaturesDescription", resourceCulture);
	}
}

/// <summary>
/// Looks up a localized string similar to Manage Group Entities.
/// </summary>
public static string ManageGroupEntities
{
	get
	{
		return ResourceManager.GetString("ManageGroupEntities", resourceCulture);
	}
}

/// <summary>
/// Looks up a localized string similar to It involves managing .
/// </summary>
public static string ManageGroupEntitiesDescription1
	{
		get
		{
			return ResourceManager.GetString("ManageGroupEntitiesDescription1", resourceCulture);
		}
	}

/// <summary>
/// Looks up a localized string similar to platform efficiently. It ensures, platform and application are running efficiently and effectively..
/// </summary>
public static string ManageGroupEntitiesDescription2
{
	get
	{
		return ResourceManager.GetString("ManageGroupEntitiesDescription2", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to App Read Only Mode Message.
/// </summary>
public static string AppReadOnlyModeMessage
{
	get
	{
		return ResourceManager.GetString("AppReadOnlyModeMessage", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to You are not authorized to access this application. Please contact your administrator..
/// </summary>
public static string AuthorizationDeniedMsg
{
	get
	{
		return ResourceManager.GetString("AuthorizationDeniedMsg", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Cannot insert NULL value.
/// </summary>
public static string NotNullConstraintMessage
{
	get
	{
		return ResourceManager.GetString("NotNullConstraintMessage", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Duplicate values are not allowed.
/// </summary>
public static string UniqueKeyViolationMessage
{
	get
	{
		return ResourceManager.GetString("UniqueKeyViolationMessage", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Please provide valid inputs.
/// </summary>
public static string CheckConstraintMessage
{
	get
	{
		return ResourceManager.GetString("CheckConstraintMessage", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Please provide unique value.
/// </summary>
public static string PrimaryKeyViolationMessage
{
	get
	{
		return ResourceManager.GetString("PrimaryKeyViolationMessage", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Please provide valid inputs.
/// </summary>
public static string ForiegnKeyViolationMessage
{
	get
	{
		return ResourceManager.GetString("ForiegnKeyViolationMessage", resourceCulture);
	}
}

/// <summary>
///   Looks up a localized string similar to Db Update Concurrency Exception.
/// </summary>
public static string ConcurrencyExceptionMessage
{
	get
	{
		return ResourceManager.GetString("ConcurrencyExceptionMessage", resourceCulture);
	}
}
/// <summary>
///   Looks up a localized string similar to Delete Exception Message.
/// </summary>
public static string DeleteExceptionMessage
{
	get
	{
		return ResourceManager.GetString("DeleteExceptionMessage", resourceCulture);
	}
}
/// <summary>
///   Looks up a localized string similar to Field Length Exception Message.
/// </summary>
public static string FieldLengthExceptionMessage
{
	get
	{
		return ResourceManager.GetString("FieldLengthExceptionMessage", resourceCulture);
	}
}

/// <summary>
/// Looks up a localized string similar to Feature1.
/// </summary>
public static string Feature1
{
	get
	{
		return ResourceManager.GetString("Feature1", resourceCulture);
	}
}

/// <summary>
/// Looks up a localized string similar to Feature2.
/// </summary>
public static string Feature2
{
	get
	{
		return ResourceManager.GetString("Feature2", resourceCulture);
	}
}

/// <summary>
/// Looks up a localized string similar to Feature3.
/// </summary>
public static string Feature3
{
	get
	{
		return ResourceManager.GetString("Feature3", resourceCulture);
	}
}

/// <summary>
/// Looks up a localized string similar to Feature4.
/// </summary>
public static string Feature4
{
	get
	{
		return ResourceManager.GetString("Feature4", resourceCulture);
	}
}

/// <summary>
/// Looks up a localized string similar to Feature5.
/// </summary>
public static string Feature5
{
	get
	{
		return ResourceManager.GetString("Feature5", resourceCulture);
	}
}

/// <summary>
/// Looks up a localized string similar to Feature6.
/// </summary>
public static string Feature6
{
	get
	{
		return ResourceManager.GetString("Feature6", resourceCulture);
	}
}

/// <summary>
/// Looks up a localized string similar to Feature7.
/// </summary>
public static string Feature7
{
	get
	{
		return ResourceManager.GetString("Feature7", resourceCulture);
	}
}

/// <summary>
/// Looks up a localized string similar to Feature8.
/// </summary>
public static string Feature8
{
	get
	{
		return ResourceManager.GetString("Feature8", resourceCulture);
	}
}

/// <summary>
/// Looks up a localized string similar to Feature9.
/// </summary>
public static string Feature9
{
	get
	{
		return ResourceManager.GetString("Feature9", resourceCulture);
	}
}

/// <summary>
/// Looks up a localized string similar to Feature10.
/// </summary>
public static string Feature10
{
	get
	{
		return ResourceManager.GetString("Feature10", resourceCulture);
	}
}

/// <summary>
/// Looks up a localized string similar to No Records Found.
/// </summary>
public static string NoRecordsFound
{
	get
	{
		return ResourceManager.GetString("NoRecordsFound", resourceCulture);
	}
}

/// <summary>
/// Looks up a localized string similar to Do you want to delete this.
/// </summary>
public static string DeleteConfirmationMessage
{
	get
	{
		return ResourceManager.GetString("DeleteConfirmationMessage", resourceCulture);
	}
}

}
}

